import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { Router } from '@angular/router';
import { finalize, forkJoin, Subscription } from 'rxjs';
import { NotificationService } from '../../core/services/notification.service';
import { UserService } from '../../core/services/user.service';
import { UserNotificationPreferences } from '../user-profile/user-profile.models';
import { NotificationDetail } from './components/notification-detail/notification-detail';
import { NotificationFeed } from './components/notification-feed/notification-feed';
import { NotificationSummary } from './components/notification-summary/notification-summary';
import { NotificationFilter, NotificationStats, SystemNotification } from './notifications.models';

@Component({selector:'app-notifications',standalone:true,imports:[NotificationSummary,NotificationFeed,NotificationDetail],templateUrl:'./notifications.html',styleUrls:['./notifications.css','./notifications-api.css']})
export class Notifications implements OnInit,OnDestroy {
  private readonly service=inject(NotificationService);private readonly userService=inject(UserService);private readonly router=inject(Router);private liveSubscription?:Subscription;
  filter:NotificationFilter='ALL';selected:SystemNotification|null=null;notice='';error='';isLoading=false;isActionPending=false;usingPreview=false;page=1;readonly pageSize=20;totalPages=1;stats:NotificationStats={inApp:0,websocket:0,smsDelivered:0,unread:0};notifications:SystemNotification[]=[];
  private readonly preview:SystemNotification[]=[{id:1,code:'NTF-081',title:'Wire Break Detected',message:'A wire break has been detected on EPF-MNR-A at SEC-004.',category:'CRITICAL',fence:'EPF-MNR-A',section:'SEC-004',time:'09:32',read:false,channels:['IN_APP','WEBSOCKET','SMS'],relatedAlert:'ALT-2847'},{id:2,code:'NTF-082',title:'Low Battery Warning',message:'Battery level at 45% on device DEV-EFE-0049.',category:'WARNING',fence:'EPF-MNR-A',section:'SEC-003',time:'08:45',read:true,channels:['IN_APP','WEBSOCKET']},{id:3,code:'NTF-083',title:'Voltage Drop Critical',message:'Voltage dropped below the critical threshold.',category:'CRITICAL',fence:'EPF-PLN-C',section:'SEC-002',time:'08:22',read:false,channels:['IN_APP','WEBSOCKET','SMS'],relatedAlert:'ALT-2844'},{id:4,code:'NTF-084',title:'Maintenance Assigned',message:'A field inspection and repair has been assigned.',category:'MAINTENANCE',fence:'EPF-MNR-A',section:'SEC-003',time:'08:15',read:true,channels:['IN_APP']},{id:5,code:'NTF-085',title:'Gateway Firmware Update',message:'Gateway firmware was updated successfully.',category:'SYSTEM',fence:'EPF-MNR-A',section:'All sections',time:'07:30',read:true,channels:['IN_APP','WEBSOCKET']},{id:6,code:'NTF-086',title:'Solar Charging Failure',message:'Solar panel reporting 0% charging efficiency.',category:'WARNING',fence:'EPF-HMB-E',section:'SEC-008',time:'07:30',read:false,channels:['IN_APP','WEBSOCKET']},{id:7,code:'NTF-087',title:'Daily Report Generated',message:'Fence health summary report is available.',category:'SYSTEM',fence:'All fences',section:'All sections',time:'06:00',read:true,channels:['IN_APP']}];
  preferences:UserNotificationPreferences={soundEnabled:true,desktopNotificationsEnabled:false,markAsReadOnOpen:true,quietHoursEnabled:false,quietHoursStart:'22:00',quietHoursEnd:'06:00',groupSimilarNotifications:true,groupingWindowMinutes:30,digestEnabled:false,digestIntervalMinutes:60};
  ngOnInit(){this.load();this.loadPreferences();this.connectLive();}ngOnDestroy(){this.liveSubscription?.unsubscribe();}get visible(){return this.usingPreview?this.previewFilter(this.notifications):this.notifications;}get unread(){return this.stats.unread;}
  changeFilter(filter:NotificationFilter){this.filter=filter;this.page=1;this.selected=null;this.loadNotifications();}
  load(){this.isLoading=true;this.error='';forkJoin({page:this.service.getNotifications({filter:this.filter,page:this.page,pageSize:this.pageSize}),stats:this.service.getStats()}).pipe(finalize(()=>this.isLoading=false)).subscribe({next:({page,stats})=>{this.usingPreview=false;this.notifications=page.items;this.totalPages=page.totalPages;this.stats=stats;},error:()=>this.usePreview()});}
  loadNotifications(){if(this.usingPreview)return;this.isLoading=true;this.service.getNotifications({filter:this.filter,page:this.page,pageSize:this.pageSize}).pipe(finalize(()=>this.isLoading=false)).subscribe({next:page=>{this.notifications=page.items;this.totalPages=page.totalPages;},error:()=>this.error='Unable to reload notifications.'});}
  retry(){this.load();}select(item:SystemNotification){this.selected=item;if(this.preferences.markAsReadOnOpen)this.markRead(item);}
  viewAlert(item:SystemNotification){if(!item.relatedAlert)return;if(!item.read)this.markRead(item);void this.router.navigate(['/alerts'],{queryParams:{alert:item.relatedAlert}});}
  markRead(item:SystemNotification){if(item.read||this.isActionPending)return;if(this.usingPreview){this.applyRead(item);return;}this.isActionPending=true;this.service.markRead(item.id).pipe(finalize(()=>this.isActionPending=false)).subscribe({next:updated=>this.applyRead(item,updated),error:()=>this.error='Unable to mark the notification as read.'});}
  markAll(){if(this.isActionPending)return;if(this.usingPreview){this.notifications.forEach(item=>item.read=true);this.refreshPreviewStats();return;}this.isActionPending=true;this.service.markAllRead().pipe(finalize(()=>this.isActionPending=false)).subscribe({next:()=>{this.notifications.forEach(item=>item.read=true);this.stats={...this.stats,unread:0};},error:()=>this.error='Unable to mark all notifications as read.'});}
  clearRead(){if(this.isActionPending)return;if(this.usingPreview){this.notifications=this.notifications.filter(item=>!item.read);if(this.selected?.read)this.selected=null;this.refreshPreviewStats();return;}this.isActionPending=true;this.service.clearRead().pipe(finalize(()=>this.isActionPending=false)).subscribe({next:()=>this.load(),error:()=>this.error='Unable to clear read notifications.'});}
  private loadPreferences(){this.userService.getNotificationPreferences().subscribe({next:value=>this.preferences=value,error:()=>{}});}
  private connectLive(){this.liveSubscription=this.service.connectLive().subscribe({next:item=>{const index=this.notifications.findIndex(current=>current.id===item.id);if(index>=0)this.notifications[index]=item;else this.notifications=[item,...this.notifications];if(!item.read)this.stats={...this.stats,inApp:this.stats.inApp+1,unread:this.stats.unread+1,websocket:this.stats.websocket+1};this.deliverBrowserNotification(item);},error:()=>{}});}
  private deliverBrowserNotification(item:SystemNotification){const silenced=item.category!=='CRITICAL'&&this.isQuietTime();if(this.preferences.soundEnabled&&!silenced)this.playNotificationTone();if(this.preferences.desktopNotificationsEnabled&&!silenced&&typeof window.Notification!=='undefined'&&window.Notification.permission==='granted')new window.Notification(item.title,{body:item.message,tag:item.relatedAlert??item.code});}
  private isQuietTime(){if(!this.preferences.quietHoursEnabled)return false;const now=new Date();const minutes=now.getHours()*60+now.getMinutes();const parse=(value:string)=>{const[hours,mins]=value.split(':').map(Number);return hours*60+mins;};const start=parse(this.preferences.quietHoursStart),end=parse(this.preferences.quietHoursEnd);return start<=end?minutes>=start&&minutes<end:minutes>=start||minutes<end;}
  private playNotificationTone(){try{const AudioContextClass=window.AudioContext;const context=new AudioContextClass();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.frequency.value=660;gain.gain.value=.04;oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.12);oscillator.onended=()=>void context.close();}catch{}}
  private applyRead(target:SystemNotification,updated?:SystemNotification){Object.assign(target,updated??{read:true});this.stats={...this.stats,unread:Math.max(0,this.stats.unread-1)};}
  private usePreview(){this.usingPreview=true;this.notifications=this.preview.map(item=>({...item,channels:[...item.channels]}));this.totalPages=1;this.error='The notification API is unavailable. Displaying local preview data.';this.refreshPreviewStats();}
  private refreshPreviewStats(){this.stats={inApp:this.notifications.length,websocket:this.notifications.filter(item=>item.channels.includes('WEBSOCKET')).length,smsDelivered:this.notifications.filter(item=>item.channels.includes('SMS')).length,unread:this.notifications.filter(item=>!item.read).length};}
  private previewFilter(items:SystemNotification[]){return items.filter(item=>this.filter==='ALL'||this.filter==='UNREAD'&&!item.read||item.category===this.filter);}
}
