import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { finalize, forkJoin, Observable, Subscription } from 'rxjs';
import { ActivatedRoute } from '@angular/router';
import { AlertService } from '../../core/services/alert.service';
import { ManagementAccessService } from '../../core/services/management-access.service';
import { AlertList } from './components/alert-list/alert-list';
import { AlertSummary } from './components/alert-summary/alert-summary';
import { IncidentPanel } from './components/incident-panel/incident-panel';
import { AlertEventType, AlertFilters, AlertRecord, AlertStats, CompleteWorkRequest, ReassignAlertRequest } from './alerts.models';

@Component({selector:'app-alerts',standalone:true,imports:[AlertSummary,AlertList,IncidentPanel],templateUrl:'./alerts.html',styleUrls:['./alerts.css','./alerts-api.css']})
export class Alerts implements OnInit,OnDestroy {
  private readonly service=inject(AlertService);private readonly route=inject(ActivatedRoute);readonly access=inject(ManagementAccessService);private liveSubscription?:Subscription;private requestedAlertCode='';
  filters:AlertFilters={severity:'',province:'',fence:'',type:'',status:'',date:''};selected:AlertRecord|null=null;notice='';error='';isLoading=false;isActionPending=false;usingPreview=false;page=1;readonly pageSize=20;totalPages=1;alerts:AlertRecord[]=[];stats:AlertStats={activeCritical:0,activeWarnings:0,unacknowledged:0,underMaintenance:0,resolvedToday:0};
  private readonly staff=[{id:101,name:'Malini Rajapaksa',email:'mrajapaksa@dwc.gov.lk',responsibility:'PRIMARY' as const,available:true},{id:102,name:'Ruwan Silva',email:'rsilva@dwc.gov.lk',responsibility:'BACKUP' as const,available:true}];
  private readonly preview:AlertRecord[]=[
    {id:1,code:'ALT-2847',title:'Wire Break Detected',type:'WIRE_BREAK',severity:'CRITICAL',province:'Uva',district:'Monaragala',fence:'EPF-MNR-A',section:'SEC-004',value:'0.0 kV',threshold:'3.0 kV',detected:'09:32:14',status:'UNACKNOWLEDGED',assignee:'Malini Rajapaksa',assigneeId:101,assignmentStatus:'AWAITING_ACCEPTANCE',assignmentSource:'AUTO_PRIMARY',assignedAt:'09:32:15',acceptanceDeadline:'09:47:15',device:'DEV-EFE-0050',comments:[],healthyReadingsReceived:0,healthyReadingsRequired:2,eligibleMaintenanceStaff:this.staff,backupUsers:[this.staff[1]],timeline:[{id:1,type:'ALERT_CREATED',label:'Alert detected',timestamp:'09:32:14'},{id:2,type:'AUTO_ASSIGNED',label:'Auto-assigned to Malini Rajapaksa',timestamp:'09:32:15'},{id:3,type:'NOTIFICATION_SENT',label:'Notification delivered',timestamp:'09:32:16',details:'In-app, WebSocket and SMS'}]},
    {id:2,code:'ALT-2846',title:'Device Offline',type:'DEVICE_OFFLINE',severity:'CRITICAL',province:'Uva',district:'Monaragala',fence:'EPF-MNR-A',section:'SEC-006',value:'No signal',threshold:'5m timeout',detected:'09:10:22',status:'ACKNOWLEDGED',assignee:'Ruwan Silva',assigneeId:102,assignmentStatus:'ACCEPTED',assignmentSource:'ADMIN_ASSIGNMENT',device:'DEV-EFE-0052',comments:[],eligibleMaintenanceStaff:this.staff},
    {id:3,code:'ALT-2845',title:'Low Battery Warning',type:'LOW_BATTERY',severity:'WARNING',province:'Uva',district:'Monaragala',fence:'EPF-MNR-A',section:'SEC-003',value:'45%',threshold:'50%',detected:'08:45:10',status:'UNDER_MAINTENANCE',assignee:'Malini Rajapaksa',assigneeId:101,assignmentStatus:'ACCEPTED',assignmentSource:'AUTO_PRIMARY',device:'DEV-EFE-0049',comments:[]},
    {id:4,code:'ALT-2844',title:'Voltage Drop Critical',type:'VOLTAGE_DROP',severity:'CRITICAL',province:'North Central',district:'Polonnaruwa',fence:'EPF-PLN-C',section:'SEC-002',value:'1.8 kV',threshold:'3.0 kV',detected:'08:22:05',status:'IN_PROGRESS',assignee:'Nimal Dissanayake',assignmentStatus:'ACCEPTED',device:'DEV-EFE-0042',comments:[]},
    {id:5,code:'ALT-2843',title:'Low Voltage Warning',type:'LOW_VOLTAGE',severity:'WARNING',province:'North Central',district:'Anuradhapura',fence:'EPF-ANR-B',section:'SEC-005',value:'4.2 kV',threshold:'5.0 kV',detected:'07:55:18',status:'RESOLVED',assignee:'Kasun Perera',assignmentStatus:'COMPLETED',resolutionType:'AUTO_RECOVERY',device:'DEV-EFE-0035',comments:[]},
    {id:6,code:'ALT-2842',title:'Solar Charging Failure',type:'SOLAR_FAILURE',severity:'WARNING',province:'Southern',district:'Hambantota',fence:'EPF-HMB-E',section:'SEC-008',value:'0%',threshold:'10%',detected:'07:30:44',status:'UNACKNOWLEDGED',assignee:'Unassigned',assignmentStatus:'UNASSIGNED',assignmentSource:'NONE',device:'DEV-EFE-0063',comments:[],eligibleMaintenanceStaff:[]}
  ];

  ngOnInit(){this.requestedAlertCode=this.route.snapshot.queryParamMap.get('alert')??'';this.load();this.connectLive();} ngOnDestroy(){this.liveSubscription?.unsubscribe();}
  get visible(){const scoped=this.alerts.filter(a=>this.access.canView(a.province,a.district));return this.usingPreview?this.applyPreviewFilters(scoped):scoped;}
  get critical(){return this.stats.activeCritical}get warnings(){return this.stats.activeWarnings}get unacknowledged(){return this.stats.unacknowledged}get maintenance(){return this.stats.underMaintenance}get resolved(){return this.stats.resolvedToday}
  get provinces(){return[...new Set(this.preview.filter(a=>this.access.canView(a.province,a.district)).map(a=>a.province))]}get fences(){return[...new Set(this.preview.filter(a=>this.access.canView(a.province,a.district)&&(!this.filters.province||a.province===this.filters.province)).map(a=>a.fence))]}get types(){return[...new Set(this.preview.map(a=>a.type))]}
  load(){this.isLoading=true;this.error='';forkJoin({page:this.service.getAlerts(this.filters,this.page,this.pageSize),stats:this.service.getStats()}).pipe(finalize(()=>this.isLoading=false)).subscribe({next:({page,stats})=>{this.usingPreview=false;this.alerts=page.items;this.totalPages=page.totalPages;this.stats=stats;this.selectRequestedAlert();},error:()=>this.usePreview()});}
  updateFilters(filters:AlertFilters){if(filters.province!==this.filters.province)filters={...filters,fence:''};this.filters=filters;this.page=1;this.selected=null;if(!this.usingPreview)this.loadAlerts();} retry(){this.load();}
  acknowledge(alert:AlertRecord){this.perform(alert,()=>this.service.acknowledge(alert.id),()=>{alert.status='ACKNOWLEDGED';alert.acknowledgedBy='Suresh Ambegoda';this.addEvent(alert,'ACKNOWLEDGED','Alert acknowledged','Suresh Ambegoda');},`${alert.code} acknowledged.`);}
  accept(alert:AlertRecord){this.perform(alert,()=>this.service.acceptAssignment(alert.id),()=>{alert.assignmentStatus='ACCEPTED';alert.status=alert.status==='UNACKNOWLEDGED'?'ACKNOWLEDGED':alert.status;this.addEvent(alert,'ASSIGNMENT_ACCEPTED','Incident assignment accepted',alert.assignee);},`${alert.code} assignment accepted.`);}
  decline(event:{alert:AlertRecord;reason:string}){this.perform(event.alert,()=>this.service.declineAssignment(event.alert.id,{reason:event.reason}),()=>{event.alert.assignmentStatus='DECLINED';this.addEvent(event.alert,'ASSIGNMENT_DECLINED','Assignment declined',event.alert.assignee,event.reason);},`${event.alert.code} assignment declined.`);}
  reassign(event:{alert:AlertRecord;request:ReassignAlertRequest}){const staff=event.alert.eligibleMaintenanceStaff?.find(item=>item.id===event.request.staffId);this.perform(event.alert,()=>this.service.reassignMaintenance(event.alert.id,event.request),()=>{const previous=event.alert.assignee;event.alert.assignee=staff?.name??'Assigned user';event.alert.assigneeId=event.request.staffId;event.alert.assignmentStatus='AWAITING_ACCEPTANCE';event.alert.assignmentSource='ADMIN_ASSIGNMENT';this.addEvent(event.alert,'REASSIGNED',`Reassigned from ${previous} to ${event.alert.assignee}`,'Suresh Ambegoda',event.request.reason);},`${event.alert.code} reassigned.`);}
  escalate(alert:AlertRecord){const backup=alert.backupUsers?.find(item=>item.available);this.perform(alert,()=>this.service.escalateAssignment(alert.id),()=>{alert.assignmentStatus='ESCALATED';this.addEvent(alert,'ESCALATED',backup?`Escalated to backup ${backup.name}`:'Escalated to responsible administrator','System');},`${alert.code} escalation started.`);}
  startWork(alert:AlertRecord){this.perform(alert,()=>this.service.startWork(alert.id),()=>{alert.status='IN_PROGRESS';this.addEvent(alert,'WORK_STARTED','Maintenance work started',alert.assignee);},`${alert.code} work started.`);}
  completeWork(event:{alert:AlertRecord;request:CompleteWorkRequest}){this.perform(event.alert,()=>this.service.completeWork(event.alert.id,event.request),()=>{event.alert.status='UNDER_MAINTENANCE';event.alert.assignmentStatus='COMPLETED';this.addEvent(event.alert,'WORK_COMPLETED','Maintenance work completed',event.alert.assignee,`${event.request.cause} · ${event.request.actions}`);},'Work completed. Waiting for healthy telemetry confirmation.');}
  resolve(event:{alert:AlertRecord;reason:string}){this.perform(event.alert,()=>this.service.resolveManually(event.alert.id,event.reason),()=>{event.alert.status='RESOLVED';event.alert.resolutionType='MANUAL';this.addEvent(event.alert,'MANUALLY_RESOLVED','Alert manually resolved','Suresh Ambegoda',event.reason);},`${event.alert.code} resolved.`);}
  addComment(event:{alert:AlertRecord;comment:string}){this.perform(event.alert,()=>this.service.addComment(event.alert.id,event.comment),()=>{event.alert.comments.push(event.comment);this.addEvent(event.alert,'COMMENT_ADDED','Investigation comment added','Current user',event.comment);},'Investigation comment added.');}
  private perform(alert:AlertRecord,request:()=>Observable<AlertRecord>,preview:()=>void,message:string){if(this.isActionPending)return;if(this.usingPreview){preview();this.notice=message;this.refreshPreviewStats();return;}this.isActionPending=true;request().pipe(finalize(()=>this.isActionPending=false)).subscribe({next:updated=>{Object.assign(alert,updated);this.notice=message;this.reloadStats();},error:()=>this.error='The incident action could not be completed.'});}
  private addEvent(alert:AlertRecord,type:AlertEventType,label:string,actor?:string,details?:string){alert.timeline=[...(alert.timeline??[]),{id:Date.now(),type,label,timestamp:new Date().toLocaleTimeString(),actor,details}];}
  private loadAlerts(){this.isLoading=true;this.service.getAlerts(this.filters,this.page,this.pageSize).pipe(finalize(()=>this.isLoading=false)).subscribe({next:page=>{this.alerts=page.items;this.totalPages=page.totalPages;},error:()=>this.error='Unable to reload alerts.'});}
  private reloadStats(){this.service.getStats().subscribe({next:stats=>this.stats=stats});}
  private connectLive(){this.liveSubscription=this.service.connectLive().subscribe({next:alert=>{if(!this.access.canView(alert.province,alert.district))return;const index=this.alerts.findIndex(item=>item.id===alert.id);if(index>=0)this.alerts[index]=alert;else this.alerts=[alert,...this.alerts];this.reloadStats();},error:()=>{}});}
  private usePreview(){this.usingPreview=true;this.alerts=this.preview.map(a=>({...a,comments:[...a.comments],timeline:[...(a.timeline??[])],eligibleMaintenanceStaff:[...(a.eligibleMaintenanceStaff??[])],backupUsers:[...(a.backupUsers??[])]}));this.totalPages=1;this.error='The alert API is unavailable. Displaying local preview data.';this.refreshPreviewStats();this.selectRequestedAlert();}
  private selectRequestedAlert(){if(!this.requestedAlertCode)return;this.selected=this.alerts.find(alert=>alert.code===this.requestedAlertCode)??null;if(!this.selected)this.error=`Related alert ${this.requestedAlertCode} is unavailable or outside your operational scope.`;}
  private refreshPreviewStats(){const items=this.alerts.filter(a=>this.access.canView(a.province,a.district));this.stats={activeCritical:items.filter(a=>a.severity==='CRITICAL'&&a.status!=='RESOLVED').length,activeWarnings:items.filter(a=>a.severity==='WARNING'&&a.status!=='RESOLVED').length,unacknowledged:items.filter(a=>a.status==='UNACKNOWLEDGED').length,underMaintenance:items.filter(a=>['ASSIGNED','IN_PROGRESS','UNDER_MAINTENANCE'].includes(a.status)).length,resolvedToday:items.filter(a=>a.status==='RESOLVED').length};}
  private applyPreviewFilters(items:AlertRecord[]){return items.filter(a=>(!this.filters.severity||a.severity===this.filters.severity)&&(!this.filters.province||a.province===this.filters.province)&&(!this.filters.fence||a.fence===this.filters.fence)&&(!this.filters.type||a.type===this.filters.type)&&(!this.filters.status||a.status===this.filters.status));}
}
